define({
    "app_name" : "Quizzes & Surveys",
    "welcome_back" : "Welcome back",
    "hello" : "Hello",
    "name" : "Name",
    "logout" : "Logout",
    "home" : "Home",
    "quizzes" : "Quizzes",
    "users" : "Users",
    "groups" : "Groups",
    "statistics" : "Statistics",
    "permissions" : "Permissions",
    "admin" : "Admin",
    "no_quiz_selected" : "No quiz selected",
    "username" : "Username",
    "firstname" : "Firstname",
    "lastname" : "Lastname",
    "type" : "Type",
    "new user" : "New user",
    "new" : "New",
    "result" : "Result",
    "resume" : "Resume",
    "forward" : "Forward",
    "backward" : "Backward",
    "done" : "Done",
    "send by e-mail" : "Send by E-mail",
    "internal server error!" : "Internal server error!",
    "invite" : "Invite",
    "invited_on" : "Invited on %{date}",
    "reinvite" : "Invite again",
    "sending" : "Sending",
    "loading" : "Loading"
});