define({
    "app_name" : "Bateria de teste",
	"welcome_back" : "Bine ai revenit",
	"hello" : "Bună",
    "name" : "Nume",
    "logout" : "Ieșire",
    "home" : "Acasă",
    "quizzes" : "Teste",
    "users" : "Utilizatori",
    "groups" : "Grupuri",
    "statistics" : "Statistici",
    "permissions" : "Permisii",
    "admin" : "Admin",
    "no_quiz_selected" : "Nici un test selectat",
    "username" : "Utilizator",
    "firstname" : "Nume",
    "lastname" : "Prenume",
    "type" : "Tip",
    "new user" : "Utilizator nou",
    "new" : "Nou",
    "result" : "Rezultat",
    "resume" : "Continuă",
    "forward" : "Înainte",
    "backward" : "Înapoi",
    "done" : "Gata",
    "send by e-mail" : "Trimite prin E-mail",
    "internal server error!" : "Eroare internă pe server!",
    "invite" : "Invită",
    "invite all" : "Invită pe toți",
    "invited_on" : "Invitat în %{date}",
    "reinvite" : "Invită din nou",
    "sending" : "Se trimite",
    "loading" : "Se încarcă",
    "templates" : "Șabloane"
});